### ISSUE TITLE
mods

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/sp19-516-122#3]
for review purposes i will now make formating cahnges with pycharm. so be carefull when you merge. I woudl recommend to do a new clone and than integarate changes you may have done. if not you can roll back, but please do better formatting

**Comment by laszewsk** [comment]
i made the modes, please check if it still works ;-)

**Comment by anthonyduer** [comment]
Got a notice when I went to push - did a pull with what you had modified and then re-pushed my changes. All seems well. :)
