### ISSUE TITLE
phase 2 of project

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/sp19-516-122#5]
you made enough progress so we can jsutify cloudmesh.emr to be in its own repository

https://github.com/cloudmesh-community/cloudmesh.emr

copy the code from project-code/cloudmesh.emr 
into this new directory (make sure to acknowlege me somewhere that i made changes)

from then on develop teh code in the new repo, fix your README.yaml to point to is and 
work not only on the code, but also a usage exampel so we can start testing on our end if possible

delete the project-code directory, so that graders are not getting confused.

we want to integrate the documentation in cloudmesh-community/cm/documentation/source/emr.md at one point but for now keep it in the new repo in readme so its easy to find

all this should probably only take 10 minutes. if you need help contact gregor via zoom

**Comment by laszewsk** [comment]
code has been copied to https://github.com/cloudmesh-community/cloudmesh.emr

please do project from now on there, delete your project-code soon so graders are not confused

**Comment by anthonyduer** [comment]
Done - using cloudmesh-emr (since names changed). Working on tail issues and working example.
